### ISSUE TITLE
Docs deployment

### ISSUE THREAD

**Issue by Sov-trotter** [QuantumBFS/YaoBlocksQobj.jl#1]
The docs have been successfully built but are not deoplyed by GHA.

**Comment by Sov-trotter** [comment]
Check if gh-pages is enabled for this repo from the settings.
Unfortunately I can't access the repo settings after the transfer
@Roger-luo  could check if gh-pages are enable for the repo?
Same for https://github.com/QuantumBFS/YaoBlocksQASM.jl 
Thanks

**Comment by Roger-luo** [comment]
I think you should have access now, can you check that?

**Comment by Sov-trotter** [comment]
Thanks. I checked. It works now
